kartoza/qgis.org.za

- django_project/flat_theme/templates/pages/index.html
Updated dates and venues in the Regional Meetups section at the bottom of the index.html front page.
> Updated text on front page

- django_project/flat_theme/templates/pages/index.html
@sokolic would you change your git repo so that your default branch is develop? Thanks
> merge changes from master to develop

- deployment/sites-enabled/default.conf
- django_project/core/settings/base.py
- django_project/core/settings/prod_docker.py
- django_project/core/settings/project.py
- django_project/core/templates/_scripts.html
- django_project/core/templates/_styles.html
- django_project/core/urls.py
- django_project/proposals/admin.py
- django_project/proposals/forms.py
- django_project/proposals/migrations/0001_initial.py
- django_project/proposals/models.py
- django_project/symposion/proposals/migrations/0004_auto_20170220_1300.py
- django_project/symposion/proposals/views.py
This and all previous commits fix #21 #23 #22
> Fix static files and sign up not working properly

- deployment/Makefile
- deployment/docker-compose.yml
- deployment/docker/REQUIREMENTS.txt
- django_project/core/settings/base.py
- django_project/core/settings/prod_docker.py
- django_project/core/settings/project.py
- django_project/core/urls.py
- django_project/symposion/templatetags/listify.py
- django_project/symposion/templatetags/markdownify.py
This fix #23 with port 80 enabled. And add several bug fixes on proposals
> Change port to 80

- deployment/Makefile
- deployment/docker/REQUIREMENTS.txt
- django_project/core/settings/contrib.py
- django_project/core/settings/prod_docker.py
- django_project/core/settings/project.py
- django_project/core/templates/dashboard.html
- django_project/core/templates/shop/list_product.html
- django_project/core/urls.py
- django_project/symposion/templatetags/pinaxcon_product_tags.py
This fix #30 . User with review permissions can review (vote) for submitted paper. It will be shown in his/her dashboard
> Add review process and ongoing category items

- deployment/sites-enabled/default.conf
Fix #https://github.com/kartoza/qgis.org.za/issues/15
> Update nginx conf

- django_project/flat_theme/templates/pages/menus/dropdown.html
Enable user to register or go to dashboard based on his login session. After user logged in, he will be brought to dashboard page, which he can submit paper, review etc
> Add link to register in homepage

- deployment/Makefile
> Add missing fixtures and reviewaccess in make deploy

- deployment/Makefile
- django_project/core/templates/symposion/schedule/_grid.html
- django_project/core/templates/symposion/schedule/schedule_conference.html
- django_project/core/templates/symposion/schedule/schedule_detail.html
- django_project/core/templates/symposion/schedule/schedule_edit.html
This fixes #89 
Show lists of schedule available on conference
> Fix conference schedule

- deployment/Makefile
- django_project/core/settings/contrib.py
- django_project/payment/checkout.py
This fixes #93 and this fixes #94
> Fix VAT, Flat Rate and from email

- django_project/core/urls.py
- django_project/payment/templates/payment/payment.html
- django_project/pinaxcon_theme/templates/shop/base.html
- django_project/pinaxcon_theme/templates/shop/billing_shipping.html
- django_project/pinaxcon_theme/templates/shop/complete.html
- django_project/pinaxcon_theme/templates/shop/includes/order_details.html
- django_project/pinaxcon_theme/templates/shop/includes/order_totals.html
- django_project/pinaxcon_theme/templates/shop/includes/order_totals.txt
- django_project/pinaxcon_theme/templates/shop/includes/order_totals_in_table.html
- django_project/symposion/templatetags/pinax_shop_tags.py
> Manual Payment

- django_project/payment/templates/payment/includes/payment-information.html
- django_project/pinaxcon_theme/templates/shop/includes/order_details.html
This fixes #95 
Payment flow now looks like in Kartoza
- Step 1
- Step 2
- Step 3
- Step 4
- Step 5
- Step Invoice
- Step Confirm Payment
> Fix payment information and invoice data

- django_project/flat_theme/static/css/style.css
> Update shop looks

- django_project/pinaxcon_theme/templates/shop/billing_shipping.html
> Fix address spell

- django_project/pinaxcon_theme/templates/shop/product.html
> Change save for later to add to wishlist

- django_project/core/adapter.py
- django_project/core/settings/project.py
- django_project/core/templates/account/email/password_reset.txt
> Reset Password

- django_project/core/templates/_default_sidebar.html
- django_project/symposion/schedule/forms.py
This fixes #130 
There are severals different quote on csv and time format need to be adjusted.
Accepted time format is "HH:MM"
> Fix upload schedule

- django_project/core/templates/symposion/schedule/_edit_grid.html
fix #133 
match room on the table and in the csv file
> edit schedule layout

- django_project/core/templates/symposion/schedule/_grid.html
> fix schedule summary layout

- django_project/core/templates/symposion/sponsorship/packages.html
- django_project/symposion/sponsorship/urls.py
- django_project/symposion/sponsorship/views.py
> add sponsor packages page

- django_project/core/templates/theme_bootstrap/base.html
> modify page header

- django_project/core/templates/_account_bar.html
> add cart menu

- django_project/core/templates/account/_signup_sidebar.html
> Change signup url

- django_project/core/templates/_default_sidebar.html
> Remove width logo

- django_project/pinaxcon_theme/templates/pages/category.html
> Fix nested cartridge menu

- django_project/pinaxcon_theme/templates/shop/includes/order_details.html
> edit order details html

- django_project/core/templates/_account_bar.html
> IAdd home link

- django_project/core/base_static/css/site.css
- django_project/core/templates/dashboard.html
> fix products dashboard layout

- django_project/core/urls.py
- django_project/pinaxcon_theme/templates/shop/purchased_items.html
- django_project/pinaxcon_theme/urls.py
- django_project/pinaxcon_theme/views.py
> List of purchased item

- django_project/core/templates/_account_bar.html
- django_project/pinaxcon_theme/urls.py
Add a link to history of purchased items
> Add purchased items
